"""Fix upload_history schema

Revision ID: 1b325da1d245
Revises: 001_initial_schema
Create Date: 2025-08-08 21:09:38.389781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b325da1d245'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qa_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processing_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
        batch_op.alter_column('file_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_upload_date'))
        batch_op.create_index('idx_upload_uploaded_at', ['uploaded_at'], unique=False)
        batch_op.drop_column('processing_completed_at')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('extracted_qa_count')
        batch_op.drop_column('total_messages')
        batch_op.drop_column('processing_started_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_started_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('total_messages', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('extracted_qa_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('processing_completed_at', sa.DATETIME(), nullable=True))
        batch_op.drop_index('idx_upload_uploaded_at')
        batch_op.create_index(batch_op.f('idx_upload_date'), ['created_at'], unique=False)
        batch_op.alter_column('file_hash',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('processing_time')
        batch_op.drop_column('qa_count')

    # ### end Alembic commands ###
